### ISSUE TITLE
After app into background then  back to app the Loop video has stopped

### ISSUE THREAD

**Issue by hungwei0331** [kschaller/ios-video-background-swift#2]
While I used this app,

I Pressed the homeBtn,

then go back this app,

the video loop stop suddenly,

I am wondering how to fix this problem,

Thanks for any comment in advance

**Comment by kschaller** [comment]
You can pause and play the background video as needed by observing changes in app state. For example, you could listen for `UIApplicationWillResignActiveNotification` and `UIApplicationWillEnterForegroundNotification` and act on those accordingly.
