### ISSUE TITLE
I changed the video to another video and the other video has another extension witch is mp4 and a problem happened.

### ISSUE THREAD

**Issue by Lopezthemogul** [kschaller/ios-video-background-swift#3]
Here is the line of code where it says that there is a problem.

 let videoURL: NSURL = NSBundle.mainBundle().URLForResource("drone", withExtension: "mov")!

When I ran the app this appeared in the debugger section "fatal error: unexpectedly found nil while unwrapping an Optional value".
How can I fix this?

<img width="900" alt="screen shot 2016-05-21 at 10 34 30 pm" src="https://cloud.githubusercontent.com/assets/16038916/15452009/3dc75626-1fa4-11e6-9155-041ca2dc3e0e.png">

**Comment by kschaller** [comment]
The `URLForResource:_:withExtension:` function returns an optional, which may be `nil` if the file you're trying to load doesn't exist in the bundle. You can prevent the crash by either
1. Ensuring that `drone.mov` exists before running your code, in which case the force unwrap will work just fine or
2. Changing line 21 to an `if let` to allow it to fail gracefully.
